vim9script

# Use comma as the prefix for custom mappings
g:mapleader = ','

# Enable syntax highlighting
syntax on

# Enable filetype plugins & indent files
filetype plugin indent on

# Don't create backup files
set nowb

# Show line numbers
set number
